name: Merged Branch

on:
  pull_request:
    types: [closed]
    branches: [ develop, main ]

jobs:
  merged_feature_into_develop:
    if: github.event.pull_request.merged == true && github.base_ref == 'develop' && startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Increment minor version
        run: |
          VERSION=$(cat version.txt)
          NEW_VERSION=$(commands/semver.sh bump minor "$VERSION")
          echo "$NEW_VERSION-SNAPSHOT" > version.txt
      - name: Push new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New feature merged and minor version bumped
          branch: ${{ github.base_ref }}

  merged_develop_into_main:
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && github.head_ref == 'develop'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      deployments: write
      
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Drop snapshot
        run: |
          VERSION=$(cat version.txt)
          NEW_VERSION="${VERSION%-SNAPSHOT}"
          echo "$NEW_VERSION" version.txt
          echo "igor_version=$NEW_VERSION" >> $GITHUB_ENV    
      - name: Push new version
        id: push_new_version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New features merged
          branch: ${{ github.base_ref }}
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.igor_version }}
          commit_sha: ${{ steps.push_new_version.outputs.commit_hash }}
      - name: Archive Igor
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'igor-${{ env.igor_version }}.zip'
          exclusions: '.gitignore .github .git install.sh'
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "igor-${{ env.igor_version }}.zip"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          tag: ${{ env.igor_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
